# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelves',
            name='score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
